<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ARI.Core-f9caf1c1-b2ea-4e29-bcc9-19eb3eb245aa</UserSecretsId>
  </PropertyGroup>
	
  <ItemGroup>
  	<Content Include="..\compose.yaml">
  		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  		<Link>compose.yaml</Link>
  	</Content>
  	<Content Include="..\\.env">
  		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  		<Link>.env</Link>
  	</Content>
  	<Content Include="..\ARI.LLM\AriModels.json">
  		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  		<Link>AriModels.json</Link>
  	</Content>
  	<Content Include="..\ARI.Brain\AriBrain.json">
  		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  		<Link>AriBrain.json</Link>
  	</Content>
  	<Content Include="..\ARI.WebPanel\wwwroot\**\*">
  		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  		<LinkBase>wwwroot</LinkBase>
  	</Content>
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\ARI.Brain\ARI.Brain.csproj" />
    <ProjectReference Include="..\ARI.Discord\ARI.Discord.csproj" />
    <ProjectReference Include="..\ARI.LLM\ARI.LLM.csproj" />
    <ProjectReference Include="..\ARI.WebPanel\ARI.WebPanel.csproj" />
  </ItemGroup>
</Project>
