using System.Text.Json.Serialization;

namespace ARI.LLM;

/// <summary>The lifecycle of a response as it is generated.</summary>
public enum AriResponseState { Streaming, Complete, Error, Cancelled }

/// <summary>One step in the agent-loop trace (deep-inspection panel). <see cref="Kind"/> is one of
/// "prompt", "reasoning", "tool_call", "tool_result", or "text".</summary>
public sealed class TraceStep
{
    public string  Kind { get; set; } = "";
    public string? Text { get; set; }   // prompt / reasoning / tool_result / text body
    public string? Name { get; set; }   // tool name (tool_call, tool_result)
    public string? Args { get; set; }   // tool args JSON (tool_call)
}

/// <summary>A response generated by ARI. Created when generation starts and streamed into.</summary>
public class AriResponse : ThreadItem
{
    public AriResponseState State { get; set; } = AriResponseState.Streaming;

    /// <summary>The ordered text and card blocks that make up this response.</summary>
    [JsonIgnore]
    public List<AriContentBlock> Content { get; set; } = new();

    /// <summary>Accumulated text during streaming; null once the response is complete.</summary>
    [JsonIgnore]
    internal string? StreamText { get; set; }

    /// <summary>The rendered string sent to clients — live text while streaming, parsed blocks once complete.</summary>
    [JsonPropertyName("content")]
    public string ContentText => StreamText ?? string.Concat(Content.Select(b => b.ToString()));

    /// <summary>True while the response is being generated; serialised so watching clients can show a typing indicator.</summary>
    [JsonPropertyName("isStreaming")]
    public bool IsStreamingJson => State == AriResponseState.Streaming;

    public double?          ThinkingSeconds { get; set; }
    public string?          RecallNotes     { get; set; }
    public string?          ContextSummary  { get; set; }
    public int              CompletionTokens          { get; set; }
    public int              OutputTokenLimit          { get; set; }
    public int              PromptTokens              { get; set; }
    public int              ContextTokenLimit         { get; set; }
    public bool             HadImageAttachments       { get; set; }
    public int              EstimatedTextPromptTokens { get; set; }
    public int              ImageTokenLimit           { get; set; }

    /// <summary>A response shown to the user but never re-entered into the model's context — e.g. a Coder
    /// sub-agent's work mirrored into the orchestrator's thread for live display. The orchestrator (architect)
    /// receives a lean summary instead, so its context stays small.</summary>
    [JsonIgnore] internal bool UiOnly { get; set; }

    // Only a completed response contributes to the LLM context window. A partial response that
    // errored or was cancelled stays visible in the thread but never re-enters the model's input.
    public override string? Message    => State == AriResponseState.Complete ? ContentText : null;
    public override string  AuthorName => "ARI";

    // What re-enters the model's context on later turns: prose only. The tool-use cards and
    // batch markers are UI display markup — feeding them back wastes tokens and teaches the
    // model to imitate angle-bracket pseudo-markup (a source of tool-call format drift).
    // UiOnly responses (mirrored sub-agent work) never re-enter context.
    public override string? ContextText => (UiOnly || State != AriResponseState.Complete)
        ? null
        : string.Concat(Content.OfType<TextBlock>().Select(b => b.Text))
              .Replace("<!--ari-batch-end-->", "")
              .Trim();

    /// <summary>The full JSON body sent to /v1/chat/completions for the final turn. Debug only — never sent to the LLM or included in normal history serialisation.</summary>
    [JsonIgnore]
    public string? DebugRequestJson  { get; set; }
    /// <summary>The assembled model response text for the final turn. Debug only — never sent to the LLM or included in normal history serialisation.</summary>
    [JsonIgnore]
    public string? DebugResponseText { get; set; }
    /// <summary>The model's raw reasoning / chain-of-thought (the streamed reasoning_content) for this turn,
    /// concatenated across the turn's requests. Debug only — never sent back to the LLM or shown in normal chat.</summary>
    [JsonIgnore]
    public string? Reasoning { get; set; }

    /// <summary>Ordered trace of the agent loop for the deep-inspection panel: the prompt, then per request
    /// the model's reasoning, each tool call and its result, and any closing prose — the full call-and-response
    /// between the model and its tools. Debug only — never sent back to the LLM or shown in normal chat.</summary>
    [JsonIgnore]
    public List<TraceStep>? Trace { get; set; }

    public override string ToString()
    {
        var sb = new System.Text.StringBuilder();
        sb.Append($"[{Timestamp:HH:mm}] A·R·I (thought for {ThinkingSeconds:F1}s):");
        if (RecallNotes != null)
        {
            var names = System.Text.RegularExpressions.Regex.Matches(RecallNotes, @"^\[([^|\]]+)", System.Text.RegularExpressions.RegexOptions.Multiline)
                            .Select(m => $"[{m.Groups[1].Value}]");
            sb.Append($"\n  Recalled Notes: {string.Join(", ", names)}");
        }
        sb.Append($"\n  {ContentText}");
        return sb.ToString();
    }
}
