namespace ARI.LLM;

/// <summary>A response generated by ARI.</summary>
public class AriResponse : ThreadItem
{
    public required string Content         { get; init; }
    public double?         ThinkingSeconds { get; init; }
    public string?         RecallNotes     { get; init; }
    public string?         ContextSummary  { get; init; }
    public int             CompletionTokens        { get; init; }
    public int             OutputTokenLimit        { get; init; }
    public int             PromptTokens            { get; init; }
    public int             ContextTokenLimit       { get; init; }
    public bool            HadImageAttachments       { get; init; }
    public int             EstimatedTextPromptTokens { get; init; }
    public int             ImageTokenLimit           { get; init; }

    public override string? Message    => Content;
    public override string  AuthorName => "ARI";

    public override string ToString()
    {
        var sb = new System.Text.StringBuilder();
        sb.Append($"[{Timestamp:HH:mm}] A·R·I (thought for {ThinkingSeconds:F1}s):");
        if (RecallNotes != null)
        {
            var names = System.Text.RegularExpressions.Regex.Matches(RecallNotes, @"^\[([^|\]]+)", System.Text.RegularExpressions.RegexOptions.Multiline)
                            .Select(m => $"[{m.Groups[1].Value}]");
            sb.Append($"\n  Recalled Notes: {string.Join(", ", names)}");
        }
        sb.Append($"\n  {Content}");
        return sb.ToString();
    }
}
