namespace ARI.LLM;

/// <summary>A response generated by ARI.</summary>
public class AriResponse : ThreadItem
{
    public required string Content         { get; init; }
    public double?         ThinkingSeconds { get; init; }
    public string?         RecallNotes     { get; init; }
    public string?         ContextSummary  { get; init; }

    public override string? Message    => Content;
    public override string  AuthorName => "ARI";
}
