using System.Text.Json.Serialization;

namespace ARI.LLM;

/// <summary>One step in the agent-loop trace (deep-inspection panel). <see cref="Kind"/> is one of
/// "prompt", "reasoning", "tool_call", "tool_result", or "text".</summary>
public sealed class TraceStep
{
    public string  Kind { get; set; } = "";
    public string? Text { get; set; }   // prompt / reasoning / tool_result / text body
    public string? Name { get; set; }   // tool name (tool_call, tool_result)
    public string? Args { get; set; }   // tool args JSON (tool_call)
}

/// <summary>A response generated by ARI. Created when generation starts and streamed into.</summary>
public class Response : ThreadItem
{
    public State State { get; set; } = State.Streaming;

    /// <summary>The ordered text and card blocks that make up this response.</summary>
    [JsonIgnore]
    public List<ContentBlock> Content { get; set; } = new();

    /// <summary>Accumulated text during streaming; null once the response is complete.</summary>
    [JsonIgnore]
    internal string? StreamText { get; set; }

    /// <summary>The rendered string sent to clients — live text while streaming, parsed blocks once complete.</summary>
    [JsonPropertyName("content")]
    public string ContentText => StreamText ?? string.Concat(Content.Select(b => b.ToString()));

    /// <summary>Child threads this response spawned, keyed by thread key. A <see cref="Subthread"/> anchor block
    /// in <see cref="Content"/> references one of these; the child's blocks are spliced into the display view
    /// here, never into context — so a sub-agent's work shows inline yet cannot contaminate the parent's context.</summary>
    [JsonIgnore]
    internal Dictionary<string, ARI.LLM.Thread> Subthreads { get; } = new();

    /// <summary>The typed block list sent to clients — the canonical, single source of truth for rendering.
    /// While streaming, derived live from the stream buffer (so it is identical before and after completion —
    /// nothing rendered can later disappear); once complete, the materialised <see cref="Content"/>. Each
    /// <see cref="Subthread"/> anchor is resolved to its child thread's display blocks (spliced in for display
    /// only). Hidden blocks (IsVisible=false) are sent so the client can decide, but never their AdditionalContext.</summary>
    [JsonPropertyName("blocks")]
    public IReadOnlyList<ContentBlock> Blocks
    {
        get
        {
            List<ContentBlock> blocks = Content.Count > 0 ? Content : ContentBlock.Parse(ContentText);
            foreach (Subthread sub in blocks.OfType<Subthread>())
                sub.Blocks = Subthreads.TryGetValue(sub.ChildKey, out ARI.LLM.Thread? child)
                    ? child.DisplayBlocks()
                    : sub.Blocks;
            return blocks;
        }
    }

    /// <summary>True while the response is being generated; serialised so watching clients can show a typing indicator.</summary>
    [JsonPropertyName("isStreaming")]
    public bool IsStreamingJson => State == State.Streaming;

    /// <summary>Wall-clock split of this turn (see Agent.TurnClock). ThinkingSeconds counts ONLY time spent
    /// receiving reasoning deltas; PrefillSeconds is the server reading the prompt (request sent → first
    /// delta, summed per request); TypingSeconds is time receiving answer/tool-call deltas. TotalSeconds is
    /// the whole turn — anything above the three buckets' sum is tool execution or stream stalls.</summary>
    public double?          ThinkingSeconds { get; set; }
    public double?          PrefillSeconds  { get; set; }
    public double?          TypingSeconds   { get; set; }
    public double?          TotalSeconds    { get; set; }
    public string?          RecallNotes     { get; set; }
    public string?          ContextSummary  { get; set; }

    /// <summary>Prompt-appraisal telemetry (DTI only): the grade the Appraisal agent gave this turn's prompt
    /// and the wall-clock thinking budget (seconds) it mapped to. Null when the turn was not appraised.</summary>
    public int?             AppraisalGrade   { get; set; }
    public int?             AppraisalSeconds { get; set; }

    /// <summary>Grouped telemetry + debug-dump fields (token stats, request/response dumps).</summary>
    public ResponseData     Data { get; set; } = new();

    /// <summary>A response shown to the user but never re-entered into the model's context — e.g. a Coder
    /// sub-agent's work mirrored into the orchestrator's thread for live display. The orchestrator (architect)
    /// receives a lean summary instead, so its context stays small.</summary>
    [JsonIgnore] internal bool UiOnly { get; set; }

    // Only a completed response contributes to the LLM context window. A partial response that
    // errored or was cancelled stays visible in the thread but never re-enters the model's input.
    [JsonIgnore]
    public override string? Message => State == State.Complete ? ContentText : null;
    public override string  AuthorName { get; init; } = "ARI";

    // What re-enters the model's context on later turns: prose only. The tool-use cards and
    // batch markers are UI display markup — feeding them back wastes tokens and teaches the
    // model to imitate angle-bracket pseudo-markup (a source of tool-call format drift).
    // UiOnly responses (mirrored sub-agent work) never re-enter context.
    [JsonIgnore]
    public override string? ContextText => (UiOnly || State != State.Complete)
        ? null
        : string.Concat(Content.OfType<TextBlock>().Select(b => b.Text))
              .Replace("<!--ari-batch-end-->", "")
              .Trim();

    /// <summary>The model's raw reasoning / chain-of-thought (the streamed reasoning_content) for this turn,
    /// concatenated across the turn's requests. Debug only — never sent back to the LLM or shown in normal chat.</summary>
    [JsonIgnore]
    public string? Reasoning { get; set; }

    /// <summary>Ordered trace of the agent loop for the deep-inspection panel: the prompt, then per request
    /// the model's reasoning, each tool call and its result, and any closing prose — the full call-and-response
    /// between the model and its tools. Debug only — never sent back to the LLM or shown in normal chat.</summary>
    [JsonIgnore]
    public List<TraceStep>? Trace { get; set; }

    public override string ToString()
    {
        var sb = new System.Text.StringBuilder();
        sb.Append($"[{Timestamp:HH:mm}] A·R·I (thought for {ThinkingSeconds:F1}s):");
        if (RecallNotes != null)
        {
            var names = System.Text.RegularExpressions.Regex.Matches(RecallNotes, @"^\[([^|\]]+)", System.Text.RegularExpressions.RegexOptions.Multiline)
                            .Select(m => $"[{m.Groups[1].Value}]");
            sb.Append($"\n  Recalled Notes: {string.Join(", ", names)}");
        }
        sb.Append($"\n  {ContentText}");
        return sb.ToString();
    }
}
